(function(root){
  'use strict';

  const c=(label,pattern,flags='i')=>({type:'command',label,pattern,flags});
  const h=(label,pattern,flags='i')=>({type:'history',label,pattern,flags});
  const s=(type,label,value,extra={})=>({type,label,value,...extra});
  const task=(slug,title,description,objective,example,checks,hints,concepts,difficulty=1,kind='Practice')=>({slug,title,description,objective,example,checks,hints:Array.isArray(hints)?hints:[hints],concepts,difficulty,kind});
  const track=(id,title,subtitle,tasks)=>({id,title,subtitle,tasks});

  const tracks=[
    track('fundamentals','Shell Fundamentals','10 reps · orientation',[
      task('pwd','Know where you are','Every shell session starts with context. Print the absolute path of your current working directory.','Display your current directory.','pwd',[c('Run `pwd`','^\s*pwd\s*$')],'`pwd` means print working directory.',['navigation','pwd'],1),
      task('ls','Read a directory','Inspect the contents of your home directory before changing anything.','List the current directory.','ls',[c('Run `ls`','^\s*ls\s*$')],'Use `ls` with no arguments.',['navigation','ls'],1),
      task('ls-all','See hidden state','Linux hides dotfiles by default. Reveal them together with long metadata.','List all entries in long format.','ls -la',[c('Use long + all flags','^\s*ls\s+-(?:la|al)\s*$')],'Combine `-l` and `-a`.',['ls','dotfiles'],1),
      task('cd-var-log','Move with intent','System logs live under `/var/log`. Navigate there using an absolute path.','Change directory to `/var/log`.','cd /var/log',[c('Enter `/var/log`','^\s*cd\s+/var/log/?\s*$'),s('cwd','Working directory is `/var/log`','/var/log')],'`cd` changes the working directory.',['navigation','absolute paths'],1),
      task('cd-home','Return home','Use shell expansion instead of typing the full home path.','Return to your home directory with `~`.','cd ~',[c('Use tilde expansion','^\s*cd\s+~/?\s*$'),s('cwd','Working directory is your home','/home/student')],'`~` expands to your home directory.',['navigation','tilde'],1),
      task('cd-parent','Move upward','Relative paths are faster when you already know where you are.','Move to the parent directory.','cd ..',[c('Use `..`','^\s*cd\s+\.\.\s*$')],'`..` represents the parent directory.',['relative paths'],1),
      task('which-bash','Locate a program','Find which executable will run when you type `bash`.','Locate the Bash executable.','which bash',[c('Locate Bash','^\s*which\s+bash\s*$')],'`which` searches your PATH.',['PATH','executables'],2),
      task('history','Inspect command history','Shell history is a productivity tool and an audit trail.','Print the command history.','history',[c('Print history','^\s*history\s*$')],'Use the `history` builtin.',['history'],1),
      task('uname','Inspect the kernel','Identify the simulated machine and kernel in one command.','Print full system information.','uname -a',[c('Use `uname -a`','^\s*uname\s+-a\s*$')],'`-a` asks for all available uname fields.',['kernel','system info'],2),
      task('hostname','Identify the host','Know which machine you are operating before making changes.','Print the hostname.','hostname',[c('Print hostname','^\s*hostname\s*$')],'The command is simply `hostname`.',['host identity'],1)
    ]),

    track('filesystem','Files & Directories','10 reps · stateful filesystem',[
      task('touch','Create a file','Create an empty marker file in your home directory.','Create `lab.txt`.','touch lab.txt',[c('Create `lab.txt`','^\s*touch\s+lab\.txt\s*$'),s('exists','`lab.txt` exists','/home/student/lab.txt')],'Use `touch filename`.',['files','touch'],1),
      task('mkdir','Create a directory','Separate work into a dedicated directory.','Create a directory named `sandbox`.','mkdir sandbox',[c('Create `sandbox`','^\s*mkdir\s+sandbox\s*$'),s('exists','`sandbox` exists','/home/student/sandbox')],'Use `mkdir`.',['directories'],1),
      task('mkdir-p','Build a directory tree','Create nested directories in one operation.','Create `projects/demo/src`.','mkdir -p projects/demo/src',[c('Use recursive creation','^\s*mkdir\s+-p\s+projects/demo/src/?\s*$'),s('exists','Nested directory exists','/home/student/projects/demo/src')],'`mkdir -p` creates missing parents.',['directories','-p'],2),
      task('copy','Copy safely','Preserve the original notes while making a working copy.','Copy `notes.txt` to `notes-copy.txt`.','cp notes.txt notes-copy.txt',[c('Copy the file','^\s*cp\s+notes\.txt\s+notes-copy\.txt\s*$'),s('exists','Copy exists','/home/student/notes-copy.txt')],'`cp source destination`.',['cp'],1),
      task('move','Rename precisely','Rename the working copy without changing its contents.','Rename `notes-copy.txt` to `archive.txt`.','mv notes-copy.txt archive.txt',[c('Rename the file','^\s*mv\s+notes-copy\.txt\s+archive\.txt\s*$'),s('exists','`archive.txt` exists','/home/student/archive.txt')],'`mv` also renames files.',['mv'],1),
      task('redirect','Write with redirection','Create a small status file using standard output redirection.','Write `ready` into `status.txt`.','echo ready > status.txt',[c('Redirect into the file','^\s*echo\s+.+\s+>\s*status\.txt\s*$'),s('fileContains','`status.txt` contains `ready`','/home/student/status.txt',{contains:'ready'})],'`>` replaces the destination file with stdout.',['redirection','stdout'],2),
      task('append','Append without destroying data','Add another line while preserving the current content.','Append `next` to `status.txt`.','echo next >> status.txt',[c('Append with `>>`','^\s*echo\s+.+\s+>>\s*status\.txt\s*$'),s('fileContains','`status.txt` contains `next`','/home/student/status.txt',{contains:'next'})],'`>>` appends instead of replacing.',['redirection','append'],2),
      task('cat','Read a file','Verify the file from the shell instead of trusting the write operation.','Print `status.txt`.','cat status.txt',[c('Read `status.txt`','^\s*cat\s+status\.txt\s*$')],'Use `cat`.',['cat'],1),
      task('remove','Remove a file','Delete the renamed archive while leaving the original notes intact.','Remove `archive.txt`.','rm archive.txt',[c('Remove `archive.txt`','^\s*rm\s+archive\.txt\s*$'),s('missing','`archive.txt` is gone','/home/student/archive.txt')],'Use `rm filename`.',['rm'],1),
      task('find','Search the tree','Find text files without manually traversing the directory tree.','Find `.txt` files below your home directory.','find . -name "*.txt"',[c('Use `find` with `-name`','^\s*find\s+\.\s+-name\s+[\'\"]?\*\.txt[\'\"]?\s*$')],'`find START -name PATTERN` searches recursively.',['find','globs'],3)
    ]),

    track('text','Text & Pipelines','10 reps · streams and filters',[
      task('grep','Find matching lines','Logs are only useful if you can filter them quickly.','Find lines containing `ERROR` in `app.log`.','grep ERROR app.log',[c('Filter `ERROR` lines','^\s*grep\s+ERROR\s+app\.log\s*$')],'`grep PATTERN FILE`.',['grep'],1),
      task('grep-i','Search case-insensitively','Incident data is rarely consistent in capitalization.','Find `timeout` regardless of case.','grep -i timeout app.log',[c('Use case-insensitive grep','^\s*grep\s+-i\s+timeout\s+app\.log\s*$')],'Use `grep -i`.',['grep','case'],2),
      task('head','Sample the beginning','Inspect a small sample before processing a large file.','Print the first 3 lines of `app.log`.','head -n 3 app.log',[c('Read first three lines','^\s*head\s+(?:-n\s+3|-3)\s+app\.log\s*$')],'`head -n 3 FILE`.',['head'],1),
      task('tail','Inspect recent output','Operational work often starts at the end of a log.','Print the last 5 lines of `app.log`.','tail -n 5 app.log',[c('Read last five lines','^\s*tail\s+(?:-n\s+5|-5)\s+app\.log\s*$')],'Use `tail -n 5`.',['tail','logs'],1),
      task('wc','Count lines','Turn raw text into a simple metric.','Count lines in `app.log`.','wc -l app.log',[c('Count lines','^\s*wc\s+-l\s+app\.log\s*$')],'`wc -l` counts newline-delimited records.',['wc'],1),
      task('sort','Sort records','Normalize unordered input before deduplication or comparison.','Sort `inventory.txt`.','sort inventory.txt',[c('Sort inventory','^\s*sort\s+inventory\.txt\s*$')],'Use `sort FILE`.',['sort'],1),
      task('uniq','Deduplicate a stream','`uniq` works best on already sorted input.','Print unique sorted lines from `inventory.txt`.','sort inventory.txt | uniq',[c('Build a sort/uniq pipeline','^\s*sort\s+inventory\.txt\s*\|\s*uniq\s*$')],'Pipe `sort` into `uniq`.',['pipes','uniq'],2),
      task('cut','Extract a CSV field','Select one column from structured delimited text.','Print the first field of `users.csv`.','cut -d, -f1 users.csv',[c('Extract field one','^\s*cut\s+-d\s*[,]?\s+-f\s*1\s+users\.csv\s*$')],'Use comma as the delimiter and field 1.',['cut','CSV'],3),
      task('tr','Transform characters','Normalize a stream without opening an editor.','Convert lowercase output to uppercase.','echo linux | tr a-z A-Z',[c('Translate character ranges','^\s*echo\s+linux\s*\|\s*tr\s+a-z\s+A-Z\s*$')],'`tr a-z A-Z` maps lowercase to uppercase.',['tr','pipes'],2),
      task('pipeline-count','Compose filters','Combine tools so each command does one job well.','Count `ERROR` lines in `app.log`.','grep ERROR app.log | wc -l',[c('Filter then count','^\s*grep\s+ERROR\s+app\.log\s*\|\s*wc\s+-l\s*$')],'Pipe matching lines into `wc -l`.',['pipes','grep','wc'],3)
    ]),

    track('permissions','Permissions & Identity','10 reps · users and modes',[
      task('whoami','Confirm identity','Never assume which account owns your shell.','Print the current username.','whoami',[c('Run `whoami`','^\s*whoami\s*$')],'Use `whoami`.',['identity'],1),
      task('id','Inspect identity details','UIDs and GIDs are what the kernel actually evaluates.','Display your UID and group membership.','id',[c('Run `id`','^\s*id\s*$')],'Use `id`.',['uid','gid'],1),
      task('groups','List groups','Supplementary groups often explain unexpected access.','Display your groups.','groups',[c('Run `groups`','^\s*groups\s*$')],'Use `groups`.',['groups'],1),
      task('ls-mode','Read mode bits','Practice reading executable and writable bits from long listings.','Inspect `deploy.sh` with a long listing.','ls -l deploy.sh',[c('Long-list the script','^\s*ls\s+-l\s+deploy\.sh\s*$')],'`ls -l` shows permissions.',['permissions','ls'],1),
      task('chmod-x','Make executable','Scripts need the executable bit when launched directly.','Add execute permission to `deploy.sh`.','chmod +x deploy.sh',[c('Add execute permission','^\s*chmod\s+\+x\s+deploy\.sh\s*$'),s('executable','Script is executable','/home/student/deploy.sh')],'Use symbolic mode `+x`.',['chmod','execute'],2),
      task('chmod-640','Set an explicit mode','Protect a secret so only the owner can write it and the group can read it.','Set `secrets.txt` to mode `640`.','chmod 640 secrets.txt',[c('Set octal mode 640','^\s*chmod\s+640\s+secrets\.txt\s*$'),s('mode','Mode is 640','/home/student/secrets.txt',{mode:'640'})],'Owner rw, group r, others none = 640.',['chmod','octal'],3),
      task('stat','Inspect metadata','Use a metadata-focused tool instead of inferring everything from `ls`.','Inspect `secrets.txt` with `stat`.','stat secrets.txt',[c('Run `stat`','^\s*stat\s+secrets\.txt\s*$')],'`stat FILE` exposes mode, owner, size and timestamps.',['stat'],2),
      task('umask','Check creation defaults','New file modes are constrained by the process umask.','Display the current umask.','umask',[c('Run `umask`','^\s*umask\s*$')],'Use `umask` with no arguments.',['umask'],2),
      task('chown','Set ownership','Ownership and permission bits solve different access-control problems.','Set `secrets.txt` owner and group to `student`.','chown student:student secrets.txt',[c('Set owner and group','^\s*chown\s+student:student\s+secrets\.txt\s*$'),s('owner','Owner is student','/home/student/secrets.txt',{owner:'student'})],'Syntax: `chown user:group file`.',['chown','ownership'],3),
      task('chmod-minus-x','Remove a capability','Permissions should be no broader than required.','Remove execute permission from `deploy.sh`.','chmod -x deploy.sh',[c('Remove execute permission','^\s*chmod\s+-x\s+deploy\.sh\s*$')],'Use symbolic mode `-x`.',['least privilege'],2)
    ]),

    track('processes','Processes & Jobs','10 reps · runtime control',[
      task('ps','List your processes','Start with the smallest useful process view.','Run `ps`.','ps',[c('Run `ps`','^\s*ps\s*$')],'Use `ps`.',['processes'],1),
      task('ps-aux','Inspect the system','Use the classic broad process listing.','Run `ps aux`.','ps aux',[c('Run `ps aux`','^\s*ps\s+aux\s*$')],'`aux` displays processes from all users.',['ps'],2),
      task('pgrep','Find a PID by name','Avoid visually scanning a long process table.','Find nginx process IDs.','pgrep nginx',[c('Search nginx PIDs','^\s*pgrep\s+nginx\s*$')],'Use `pgrep NAME`.',['pgrep','pid'],2),
      task('background','Start a background job','Keep the terminal available while a command runs.','Start `sleep 30` in the background.','sleep 30 &',[c('Launch a background job','^\s*sleep\s+30\s*&\s*$'),s('process','A sleep process exists','sleep')],'Append `&` to run in the background.',['jobs','background'],2),
      task('jobs','Inspect shell jobs','See jobs started from the current shell.','List background jobs.','jobs',[c('Run `jobs`','^\s*jobs\s*$')],'Use the `jobs` builtin.',['jobs'],1),
      task('kill','Stop by PID','Terminate the baseline worker using its PID.','Send TERM to PID `4242`.','kill 4242',[c('Kill PID 4242','^\s*kill\s+4242\s*$'),s('processMissing','PID 4242 is gone','4242')],'`kill PID` sends SIGTERM by default.',['signals','kill'],2),
      task('pkill','Stop by name','When the target is known by name, avoid manual PID lookup.','Terminate all `sleep` processes.','pkill sleep',[c('Kill sleep by name','^\s*pkill\s+sleep\s*$'),s('processNameMissing','No sleep process remains','sleep')],'`pkill NAME` targets processes by name.',['pkill'],2),
      task('uptime','Read load context','Process symptoms make more sense with system load context.','Display uptime and load averages.','uptime',[c('Run `uptime`','^\s*uptime\s*$')],'Use `uptime`.',['load average'],1),
      task('top','Inspect live activity','Use an interactive-style summary when you need CPU and memory context.','Run the simulated `top` view.','top',[c('Run `top`','^\s*top\s*$')],'Use `top`.',['top','runtime'],2),
      task('ps-grep','Compose process filters','Use a pipeline to focus a broad listing.','Filter `ps aux` for nginx.','ps aux | grep nginx',[c('Pipe ps into grep','^\s*ps\s+aux\s*\|\s*grep\s+nginx\s*$')],'Pipe `ps aux` into `grep nginx`.',['pipes','processes'],2)
    ]),

    track('networking','Networking','10 reps · interfaces to HTTP',[
      task('ip-addr','Inspect interfaces','Know the addresses configured on the host.','Display network interfaces and addresses.','ip addr',[c('Run `ip addr`','^\s*ip\s+(?:addr|a)\s*$')],'Use `ip addr`.',['ip','interfaces'],1),
      task('ip-route','Inspect routing','A valid address is useless if the route is wrong.','Display the routing table.','ip route',[c('Run `ip route`','^\s*ip\s+(?:route|r)\s*$')],'Use `ip route`.',['routing'],2),
      task('ss','Inspect listeners','Find which services are listening and on which ports.','List TCP/UDP listening sockets with process info.','ss -tulpn',[c('Inspect listening sockets','^\s*ss\s+-[a-z]*t[a-z]*u[a-z]*l[a-z]*p[a-z]*n[a-z]*\s*$|^\s*ss\s+-tulpn\s*$')],'`ss -tulpn` is a common listener view.',['sockets','ports'],2),
      task('ping','Test reachability','Separate basic network reachability from application-layer failures.','Send 3 ICMP probes to `example.com`.','ping -c 3 example.com',[c('Ping three times','^\s*ping\s+-c\s+3\s+example\.com\s*$')],'Use `ping -c 3 HOST`.',['icmp','ping'],1),
      task('curl','Make an HTTP request','Test an endpoint without a browser.','Fetch `https://example.com`.','curl https://example.com',[c('Fetch the URL','^\s*curl\s+https://example\.com/?\s*$')],'Use `curl URL`.',['http','curl'],1),
      task('curl-head','Inspect HTTP headers','Headers often reveal redirects, caching and server identity.','Request headers only from `https://example.com`.','curl -I https://example.com',[c('Request headers','^\s*curl\s+-I\s+https://example\.com/?\s*$')],'`-I` performs a HEAD request.',['http headers'],2),
      task('dig','Resolve DNS','Verify name resolution separately from connectivity.','Resolve `example.com`.','dig example.com',[c('Query DNS','^\s*dig\s+example\.com\s*$')],'Use `dig DOMAIN`.',['dns'],2),
      task('hostname-net','Reconfirm host identity','Network troubleshooting starts with knowing the endpoint you are on.','Print the hostname.','hostname',[c('Print hostname','^\s*hostname\s*$')],'Use `hostname`.',['host identity'],1),
      task('port-filter','Find a specific listener','Filter the socket table for HTTP port 80.','Find port `80` in the listener table.','ss -tulpn | grep :80',[c('Filter for port 80','^\s*ss\s+-tulpn\s*\|\s*grep\s+:?80\s*$')],'Pipe the socket list into `grep :80`.',['ports','pipes'],3),
      task('health','Probe application health','Operational checks should validate the application response, not only the port.','Fetch the local health endpoint and filter for `ok`.','curl -s https://api.local/health | grep ok',[c('Probe and filter health','^\s*curl\s+-s\s+https://api\.local/health\s*\|\s*grep\s+ok\s*$')],'Pipe a quiet curl response into grep.',['health checks','http'],3)
    ]),

    track('bash','Bash Scripting','10 reps · variables and scripts',[
      task('export','Set environment state','Environment variables are the simplest configuration interface for Unix programs.','Export `APP_ENV=staging`.','export APP_ENV=staging',[c('Export the variable','^\s*export\s+APP_ENV=staging\s*$'),s('env','`APP_ENV` is staging','APP_ENV',{equals:'staging'})],'Use `export NAME=value`.',['environment','export'],2),
      task('expand','Expand a variable','Verify the shell can substitute the value you just configured.','Print `$APP_ENV`.','echo $APP_ENV',[c('Expand APP_ENV','^\s*echo\s+\$APP_ENV\s*$')],'Prefix a variable name with `$`.',['variables','expansion'],2),
      task('alias','Create a shortcut','Aliases are useful for repeated interactive commands.','Create `ll` as an alias for `ls -la`.','alias ll="ls -la"',[c('Define the alias','^\s*alias\s+ll=[\'\"]ls\s+-la[\'\"]\s*$')],'Use `alias name="command"`.',['aliases'],2),
      task('use-alias','Use your alias','A shortcut only matters if the shell expands it correctly.','Run `ll`.','ll',[c('Run the alias','^\s*ll\s*$')],'Type the alias name.',['aliases'],1),
      task('shebang','Start a script','A script should identify the interpreter it expects.','Write a Bash shebang into `deploy.sh`.','echo "#!/bin/bash" > deploy.sh',[c('Write a shebang','^\s*echo\s+[\'\"]?#!\/bin\/bash[\'\"]?\s+>\s*deploy\.sh\s*$'),s('fileContains','Script contains a shebang','/home/student/deploy.sh',{contains:'#!/bin/bash'})],'Redirect `#!/bin/bash` into the file.',['shebang','scripts'],2),
      task('script-body','Add script logic','Build scripts incrementally and keep each step observable.','Append `echo deploy-ok` to `deploy.sh`.','echo "echo deploy-ok" >> deploy.sh',[c('Append script body','^\s*echo\s+[\'\"]echo\s+deploy-ok[\'\"]\s+>>\s*deploy\.sh\s*$'),s('fileContains','Script contains deploy output','/home/student/deploy.sh',{contains:'echo deploy-ok'})],'Append the command with `>>`.',['scripts','redirection'],2),
      task('script-exec','Make the script executable','Direct execution depends on both the shebang and execute permission.','Add execute permission to `deploy.sh`.','chmod +x deploy.sh',[c('Add execute permission','^\s*chmod\s+\+x\s+deploy\.sh\s*$'),s('executable','Script is executable','/home/student/deploy.sh')],'Use `chmod +x`.',['chmod','scripts'],2),
      task('run-script','Execute the script','Run your script exactly as an executable in the current directory.','Execute `./deploy.sh`.','./deploy.sh',[c('Run the script','^\s*\.\/deploy\.sh\s*$')],'Prefix the path with `./`.',['scripts','execution'],2),
      task('substitution','Use command substitution','Capture command output inside another command.','Echo the current directory using `$(pwd)`.','echo $(pwd)',[c('Use command substitution','^\s*echo\s+\$\(pwd\)\s*$')],'`$(command)` substitutes command output.',['command substitution'],3),
      task('fallback','Handle failure','Use a boolean operator to execute a fallback only when the first command fails.','Print `recovered` after `false` fails.','false || echo recovered',[c('Use the OR operator','^\s*false\s*\|\|\s*echo\s+recovered\s*$')],'`A || B` runs B when A fails.',['exit codes','boolean operators'],3)
    ]),

    track('git','Git','10 reps · repository workflow',[
      task('git-init','Initialize a repository','Turn the current project directory into a Git repository.','Initialize Git in the current directory.','git init',[c('Initialize Git','^\s*git\s+init\s*$'),s('git','Repository initialized','initialized',{equals:true})],'Use `git init`.',['git','repository'],1),
      task('git-status','Inspect repository state','Before staging or committing, understand what Git sees.','Show repository status.','git status',[c('Run `git status`','^\s*git\s+status\s*$')],'Use `git status`.',['git status'],1),
      task('git-add','Stage a change','Move one file into the index without staging everything.','Stage `README.md`.','git add README.md',[c('Stage README','^\s*git\s+add\s+README\.md\s*$'),s('gitStaged','README is staged','README.md')],'Use `git add FILE`.',['staging'],1),
      task('git-commit','Create a commit','Record the staged snapshot with a concise message.','Commit with message `initial`.','git commit -m "initial"',[c('Commit staged work','^\s*git\s+commit\s+-m\s+[\'\"]initial[\'\"]\s*$'),s('gitCommits','At least one commit exists',1,{min:1})],'Use `git commit -m "message"`.',['commits'],2),
      task('git-branch','Create a branch','Isolate feature work from the main line.','Create branch `feature/auth`.','git branch feature/auth',[c('Create feature branch','^\s*git\s+branch\s+feature/auth\s*$'),s('gitBranchExists','Feature branch exists','feature/auth')],'Use `git branch NAME`.',['branches'],2),
      task('git-switch','Switch branches','Move the working context to your feature branch.','Switch to `feature/auth`.','git switch feature/auth',[c('Switch branches','^\s*git\s+(?:switch|checkout)\s+feature/auth\s*$'),s('gitBranch','Current branch is feature/auth','feature/auth')],'Use `git switch feature/auth`.',['branches'],2),
      task('git-log','Inspect history','Read compact commit history before comparing or reverting work.','Show the oneline log.','git log --oneline',[c('Show compact log','^\s*git\s+log\s+--oneline\s*$')],'Use `git log --oneline`.',['history'],1),
      task('git-diff','Inspect unstaged changes','Review the actual diff before staging it.','Run `git diff`.','git diff',[c('Run `git diff`','^\s*git\s+diff\s*$')],'Use `git diff`.',['diff'],1),
      task('git-remote','Configure a remote','Associate the local repository with a remote named `origin`.','Add the example GitHub URL as `origin`.','git remote add origin https://github.com/example/app.git',[c('Add origin','^\s*git\s+remote\s+add\s+origin\s+https://github\.com/example/app\.git\s*$'),s('gitRemote','Origin is configured','origin')],'`git remote add NAME URL`.',['remotes'],2),
      task('git-stash','Stash work','Temporarily clear local changes without committing them.','Create a stash entry.','git stash',[c('Stash changes','^\s*git\s+stash(?:\s+push)?\s*$'),s('gitStash','A stash entry exists',1,{min:1})],'Use `git stash`.',['stash'],2)
    ]),

    track('docker','Docker','10 reps · images and containers',[
      task('docker-images','Inspect local images','Know what is already available before pulling or building.','List Docker images.','docker images',[c('List images','^\s*docker\s+images\s*$')],'Use `docker images`.',['docker','images'],1),
      task('docker-pull','Pull an image','Fetch a small web-server image into the local image cache.','Pull `nginx:alpine`.','docker pull nginx:alpine',[c('Pull nginx image','^\s*docker\s+pull\s+nginx:alpine\s*$'),s('dockerImage','Image exists','nginx:alpine')],'Use `docker pull IMAGE`.',['registry','images'],1),
      task('docker-run','Run a service','Launch nginx detached and publish it on host port 8080.','Run container `web` from `nginx:alpine` with `8080:80`.','docker run -d --name web -p 8080:80 nginx:alpine',[c('Start the web container','^\s*docker\s+run\s+.*--name\s+web.*-p\s+8080:80.*nginx:alpine\s*$'),s('dockerContainer','Container web is running','web',{status:'running'})],'Use detached mode, `--name`, and `-p`.',['containers','ports'],3),
      task('docker-ps','Inspect running containers','Confirm runtime state instead of assuming the launch succeeded.','List running containers.','docker ps',[c('List running containers','^\s*docker\s+ps\s*$')],'Use `docker ps`.',['containers'],1),
      task('docker-logs','Read container logs','Treat container stdout/stderr as an operational signal.','Read logs from `web`.','docker logs web',[c('Read web logs','^\s*docker\s+logs\s+web\s*$')],'Use `docker logs NAME`.',['logs'],2),
      task('docker-exec','Run inside a container','Execute a diagnostic command without opening an interactive shell.','Run `hostname` inside `web`.','docker exec web hostname',[c('Exec hostname','^\s*docker\s+exec\s+web\s+hostname\s*$')],'`docker exec CONTAINER COMMAND`.',['exec'],2),
      task('docker-inspect','Inspect configuration','Use structured runtime metadata when debugging container configuration.','Inspect `web`.','docker inspect web',[c('Inspect web','^\s*docker\s+inspect\s+web\s*$')],'Use `docker inspect`.',['inspect'],2),
      task('docker-stop','Stop cleanly','Prefer an orderly stop before removing a container.','Stop `web`.','docker stop web',[c('Stop web','^\s*docker\s+stop\s+web\s*$'),s('dockerContainer','Container web is stopped','web',{status:'stopped'})],'Use `docker stop NAME`.',['lifecycle'],1),
      task('docker-rm','Remove stopped state','Clean up a container after it is no longer needed.','Remove `web`.','docker rm web',[c('Remove web','^\s*docker\s+rm\s+web\s*$'),s('dockerContainerMissing','Container web is removed','web')],'Use `docker rm NAME`.',['cleanup'],1),
      task('docker-build','Build an image','Create an application image from the current project context.','Build image `linux-gym/app:dev`.','docker build -t linux-gym/app:dev .',[c('Build the app image','^\s*docker\s+build\s+-t\s+linux-gym/app:dev\s+\.\s*$'),s('dockerImage','Built image exists','linux-gym/app:dev')],'`docker build -t NAME:TAG CONTEXT`.',['build','Dockerfile'],3)
    ]),

    track('ssh','SSH & Remote','10 reps · secure remote work',[
      task('ssh-keygen','Create a keypair','Use modern public-key authentication instead of passwords.','Generate an Ed25519 keypair.','ssh-keygen -t ed25519',[c('Generate Ed25519 keys','^\s*ssh-keygen\s+-t\s+ed25519(?:\s+.*)?$'),s('exists','Private key exists','/home/student/.ssh/id_ed25519')],'Use `ssh-keygen -t ed25519`.',['ssh','keys'],2),
      task('ssh-list','Inspect SSH state','Verify which keys and config files exist.','List `~/.ssh`.','ls ~/.ssh',[c('List SSH directory','^\s*ls\s+~/?\.ssh/?\s*$')],'Use `ls ~/.ssh`.',['ssh','files'],1),
      task('ssh-mode','Protect the private key','OpenSSH rejects private keys with overly broad permissions.','Set the private key mode to `600`.','chmod 600 ~/.ssh/id_ed25519',[c('Protect private key','^\s*chmod\s+600\s+~/?\.ssh/id_ed25519\s*$'),s('mode','Private key mode is 600','/home/student/.ssh/id_ed25519',{mode:'600'})],'Private keys should normally be owner read/write only.',['permissions','ssh'],2),
      task('ssh-connect','Connect remotely','Open a simulated secure session to the development host.','Connect as `dev` to `server.local`.','ssh dev@server.local',[c('Connect to server.local','^\s*ssh\s+dev@server\.local\s*$')],'Syntax: `ssh user@host`.',['remote shell'],1),
      task('scp','Copy remotely','Transfer one local file without starting an interactive session.','Copy `status.txt` to `/tmp/status.txt` on `server.local`.','scp status.txt dev@server.local:/tmp/status.txt',[c('Copy with scp','^\s*scp\s+status\.txt\s+dev@server\.local:/tmp/status\.txt\s*$')],'`scp SOURCE user@host:DEST`.',['scp'],2),
      task('ssh-verbose','Debug connection setup','Verbose SSH output exposes DNS, key and negotiation problems.','Connect with verbose diagnostics.','ssh -v dev@server.local',[c('Use verbose SSH','^\s*ssh\s+-v\s+dev@server\.local\s*$')],'Add `-v`.',['ssh debugging'],2),
      task('ssh-fingerprint','Inspect a public key','Fingerprints are safer to compare than full key blobs.','Print the fingerprint of your public key.','ssh-keygen -lf ~/.ssh/id_ed25519.pub',[c('Print key fingerprint','^\s*ssh-keygen\s+-lf\s+~/?\.ssh/id_ed25519\.pub\s*$')],'Use `ssh-keygen -lf PUBKEY`.',['fingerprints'],3),
      task('ssh-config','Create host config','Save a host alias so routine connections are shorter and consistent.','Create `~/.ssh/config` containing `Host appbox`.','echo "Host appbox" > ~/.ssh/config',[c('Create SSH config','^\s*echo\s+[\'\"]Host\s+appbox[\'\"]\s+>\s*~/?\.ssh/config\s*$'),s('fileContains','Config contains appbox','/home/student/.ssh/config',{contains:'Host appbox'})],'Write a `Host` stanza into the config file.',['ssh config'],3),
      task('ssh-config-mode','Protect SSH config','Keep SSH configuration readable only where appropriate.','Set `~/.ssh/config` to mode `600`.','chmod 600 ~/.ssh/config',[c('Protect config','^\s*chmod\s+600\s+~/?\.ssh/config\s*$'),s('mode','Config mode is 600','/home/student/.ssh/config',{mode:'600'})],'Use `chmod 600`.',['permissions'],2),
      task('ssh-alias','Use a host alias','Operate through a stable logical host name rather than repeating connection details.','Connect to `appbox`.','ssh appbox',[c('Connect using alias','^\s*ssh\s+appbox\s*$')],'Once configured, `ssh appbox` is enough.',['ssh config','aliases'],2)
    ]),

    track('devops','DevOps Operations','10 reps · services and capacity',[
      task('service-status','Inspect a service','Check state before changing it.','Show nginx service status.','systemctl status nginx',[c('Inspect nginx','^\s*systemctl\s+status\s+nginx\s*$')],'Use `systemctl status SERVICE`.',['systemd','services'],1),
      task('service-restart','Restart a service','Apply a clean restart to recover or load configuration.','Restart nginx.','systemctl restart nginx',[c('Restart nginx','^\s*systemctl\s+restart\s+nginx\s*$'),s('service','Nginx is active','nginx',{status:'active'})],'Use `systemctl restart`.',['systemd'],2),
      task('service-enable','Persist service startup','A healthy service should return after reboot when intended.','Enable nginx at boot.','systemctl enable nginx',[c('Enable nginx','^\s*systemctl\s+enable\s+nginx\s*$'),s('serviceEnabled','Nginx is enabled','nginx')],'Use `systemctl enable`.',['boot','services'],2),
      task('journal','Read service logs','Systemd journals combine process lifecycle and application messages.','Show today’s nginx journal.','journalctl -u nginx --since today',[c('Read nginx journal','^\s*journalctl\s+-u\s+nginx\s+--since\s+today\s*$')],'Filter journal by unit and time.',['journalctl','logs'],2),
      task('disk','Inspect filesystem capacity','Capacity incidents are among the most common production failures.','Show human-readable filesystem usage.','df -h',[c('Run `df -h`','^\s*df\s+-h\s*$')],'Use `df -h`.',['disk','capacity'],1),
      task('du','Find heavy directories','Filesystem totals are only the start; locate where space is consumed.','Show total size of `/var/log`.','du -sh /var/log',[c('Measure /var/log','^\s*du\s+-sh\s+/var/log/?\s*$')],'`du -sh PATH` gives one human-readable total.',['disk usage'],2),
      task('memory','Inspect memory','Check memory pressure before blaming CPU or storage.','Show human-readable memory usage.','free -h',[c('Run `free -h`','^\s*free\s+-h\s*$')],'Use `free -h`.',['memory'],1),
      task('archive','Archive logs','Bundle multiple log files before transfer or retention.','Create `logs.tgz` from `/var/log/nginx`.','tar -czf logs.tgz /var/log/nginx',[c('Create a gzipped tarball','^\s*tar\s+-czf\s+logs\.tgz\s+/var/log/nginx/?\s*$'),s('exists','Archive exists','/home/student/logs.tgz')],'`tar -czf archive.tgz path`.',['tar','archives'],3),
      task('gzip','Compress a file','Use a single-file compressor when an archive is unnecessary.','Compress `status.txt`.','gzip status.txt',[c('Compress status.txt','^\s*gzip\s+status\.txt\s*$'),s('exists','Compressed file exists','/home/student/status.txt.gz')],'Use `gzip FILE`.',['compression'],2),
      task('uptime-ops','Read load averages','Add host age and recent load to your incident context.','Run `uptime`.','uptime',[c('Run `uptime`','^\s*uptime\s*$')],'Use `uptime`.',['load average'],1)
    ]),

    track('troubleshooting','Troubleshooting','10 reps · evidence before action',[
      task('nginx-tail','Read the latest error context','Start from the newest service errors before searching the entire log corpus.','Read the last 20 lines of nginx error log.','tail -n 20 /var/log/nginx/error.log',[c('Tail nginx errors','^\s*tail\s+-n\s+20\s+/var/log/nginx/error\.log\s*$')],'Use `tail -n 20`.',['incident response','logs'],2),
      task('failed-grep','Search failure signals','Search for explicit failure language before forming a hypothesis.','Find `failed` in the nginx error log, case-insensitively.','grep -i failed /var/log/nginx/error.log',[c('Search failed messages','^\s*grep\s+-i\s+failed\s+/var/log/nginx/error\.log\s*$')],'Use `grep -i`.',['grep','incident response'],2),
      task('port-80','Verify the listener','Confirm that HTTP is actually bound before testing the application.','Find port 80 in listening sockets.','ss -tulpn | grep :80',[c('Verify port 80','^\s*ss\s+-tulpn\s*\|\s*grep\s+:?80\s*$')],'Inspect listeners, then filter.',['ports'],2),
      task('nginx-process','Verify the process','A unit can report one thing while the process table reveals another.','Filter the process table for nginx.','ps aux | grep nginx',[c('Find nginx process','^\s*ps\s+aux\s*\|\s*grep\s+nginx\s*$')],'Pipe `ps aux` into grep.',['processes'],2),
      task('disk-check','Rule out disk pressure','Full filesystems can cause failures far from the storage layer.','Check disk capacity.','df -h',[c('Check disk usage','^\s*df\s+-h\s*$')],'Use `df -h`.',['capacity'],1),
      task('memory-check','Rule out memory pressure','Memory exhaustion changes service behavior and may trigger OOM kills.','Check memory usage.','free -h',[c('Check memory','^\s*free\s+-h\s*$')],'Use `free -h`.',['memory'],1),
      task('journal-errors','Inspect high-severity journal entries','Use severity filtering to reduce noise during an incident.','Show error-priority journal entries.','journalctl -p err',[c('Filter journal by priority','^\s*journalctl\s+-p\s+err\s*$')],'Use `journalctl -p err`.',['journalctl'],2),
      task('local-http','Test the local application path','Bypass external DNS and routing to isolate the host-local service.','Request only headers from localhost.','curl -I http://localhost',[c('Probe localhost','^\s*curl\s+-I\s+http://localhost/?\s*$')],'Use a HEAD request to localhost.',['http','isolation'],2),
      task('internal-dns','Verify internal DNS','Name resolution can fail even when the service itself is healthy.','Resolve `app.internal`.','dig app.internal',[c('Resolve app.internal','^\s*dig\s+app\.internal\s*$')],'Query the name directly with `dig`.',['dns'],2),
      task('service-final','Return to service state','After collecting evidence, re-check service state before taking action.','Show nginx service status.','systemctl status nginx',[c('Inspect final service state','^\s*systemctl\s+status\s+nginx\s*$')],'Use `systemctl status nginx`.',['systemd','triage'],2)
    ]),

    track('exams','Scenario Exams','4 exams · multi-step validation',[
      task('exam-foundation','Foundation Exam','Build a small incident evidence bundle using filesystem, text and permissions skills.','Create `/tmp/exam`, save `ERROR` lines from `~/app.log` to `/tmp/exam/errors.txt`, then set the file mode to `640`.','mkdir -p /tmp/exam && grep ERROR ~/app.log > /tmp/exam/errors.txt && chmod 640 /tmp/exam/errors.txt',[
        s('exists','`/tmp/exam/errors.txt` exists','/tmp/exam/errors.txt'),s('fileContains','The file contains an ERROR line','/tmp/exam/errors.txt',{contains:'ERROR'}),s('mode','Evidence file mode is 640','/tmp/exam/errors.txt',{mode:'640'})
      ],['Create the directory first.','Redirect grep output into the evidence file.','Finish with `chmod 640`.'],['filesystem','grep','permissions'],4,'Exam'),
      task('exam-git','Git Workflow Exam','Create a clean repository checkpoint and isolate release work on its own branch.','Initialize Git, stage `README.md`, commit it, then create and switch to branch `release`.','git init; git add README.md; git commit -m "checkpoint"; git switch -c release',[
        s('git','Repository initialized','initialized',{equals:true}),s('gitCommits','At least one commit exists',1,{min:1}),s('gitBranch','Current branch is release','release')
      ],['Initialize the repository.','Stage and commit one file.','Create and switch to `release`.'],['git','branching','commits'],4,'Exam'),
      task('exam-devops','Operations Exam','Recover the simulated web service and prove it responds locally.','Restart nginx and successfully probe `http://localhost/health`.','systemctl restart nginx && curl -s http://localhost/health',[
        s('service','Nginx is active','nginx',{status:'active'}),h('A local health probe was executed','curl\s+-s\s+http://localhost/health')
      ],['Restart nginx with systemctl.','Probe the health URL from the same host.'],['systemd','http','recovery'],5,'Exam'),
      task('exam-container','Container Exam','Deploy a disposable web container and leave it running on host port 8088.','Pull `nginx:alpine` and run it as `exam-web` with `8088:80`.','docker pull nginx:alpine && docker run -d --name exam-web -p 8088:80 nginx:alpine',[
        s('dockerImage','The nginx image exists','nginx:alpine'),s('dockerContainer','`exam-web` is running','exam-web',{status:'running',port:'8088:80'})
      ],['Pull the image first.','Run detached with a name and published port.'],['docker','deployment','ports'],5,'Exam')
    ])
  ];

  const flat=[];
  tracks.forEach((tr,ti)=>tr.tasks.forEach((t,ri)=>flat.push({...t,trackId:tr.id,trackTitle:tr.title,trackIndex:ti,taskIndex:ri,id:`${tr.id}/${t.slug}`})));

  root.LinuxGymData={tracks,tasks:flat,totalTasks:flat.length};
})(typeof globalThis!=='undefined'?globalThis:window);
